### ISSUE TITLE
Section __libc_freeres_fn not recognized

### ISSUE THREAD

**Issue by IridiumXOR** [Decompollaborate/mapfile_parser#25] opened 2024-02-23 15:25 UTC
Section ```__libc_freeres_fn``` is not recognized in maps. I suppose because it does not start with `.` as for example `.text` or `.rodata`

**Comment by AngheloAlf** [comment] 2024-02-23 23:54
Could you post the mapfile so I can test it locally?

**Comment by IridiumXOR** [comment] 2024-02-24 00:40
[Uploading vim.map.txt…]()

**Comment by IridiumXOR** [comment] 2024-02-24 00:41
[vim.zip](https://github.com/Decompollaborate/mapfile_parser/files/14391160/vim.zip)

**Comment by AngheloAlf** [comment] 2024-02-24 02:09
I just made a release that should fix this issue.

lmk if it works properly

It may take like 10 minutes to be up for download

**Comment by IridiumXOR** [comment] 2024-02-25 13:38
I have tested the new version (installed from Pip, it's the 2.3.6). I see a data section starting with `__libc_atexit` but not the executable section `__libc_freeres_fn`

**Comment by AngheloAlf** [comment] 2024-02-25 16:32
I pushed a fix to the develop branch.

Could you please test everything is okay before I make another release?

To install the develop version without cloning (you'll need Rust installed to build from source):

```bash
python3 -m pip uninstall mapfile_parser
python3 -m pip install git+https://github.com/Decompollaborate/mapfile_parser.git@develop
```

**Comment by IridiumXOR** [comment] 2024-02-25 20:21
It does not compile
```error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
          Updating crates.io index
      error: Package `mapfile_parser v2.3.6 (/tmp/pip-req-build-_ni7cvhn)` does not have feature `pyo3`. It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-38_nani8', '--interpreter', '/usr/bin/python3']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /tmp/pip-modern-metadata-38_nani8 --interpreter /usr/bin/python3`
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by AngheloAlf** [comment] 2024-02-26 00:07
iirc this error is caused by an outdated Rust/cargo installation. Try updating rust

To update:
```
$ rustup update
```

As a reference this is my local version:
```
$ cargo --version
cargo 1.75.0 (1d8b05cdd 2023-11-20)
```

**Comment by IridiumXOR** [comment] 2024-02-27 20:32
I have compiled it correctly (it was my fault, old rust version...) but the ```__libc_freeres_fn``` continue to not be in the sections..

**Comment by AngheloAlf** [comment] 2024-02-27 21:09
Could you tell me how are you testing it?

I'm testing it by using the jsonify utility:
```
$ python3 -m mapfile_parser jsonify vim.map -o vim.json
```

I can see the `__libc_freeres_fn` section on the generated json. Could you tell me what's missing?

[vim.json](https://github.com/Decompollaborate/mapfile_parser/files/14425697/vim.json)

**Comment by IridiumXOR** [comment] 2024-02-27 21:52
Ok sorry, my fault again.... I have removed the package and reinstalled it and now I correctly see the  ```__libc_freeres_fn``` entries. Sorry :(

P.S. There is another bug however, you can see it also in your json file: there are a lot of ```filepath``` entry that ends with ```__fill__``` at the end of the string

**Comment by IridiumXOR** [comment] 2024-02-27 21:53
Thanks so much for have fixed it (and replied me)!

**Comment by AngheloAlf** [comment] 2024-02-27 22:39
Sadly the `__fill__`s are required internally and there's no easy way to untangle them out.
They exist because of the actual `*fill*` entries from the mapfile, like this one:
```
 __libc_freeres_fn
                0x00000000007bdc70      0x6e5 /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libc.a(gconv_db.o)
 *fill*         0x00000000007be355        0xb 
```

Currently the only workaround I can think of is to manually filter them out on the user's side.
I agree it would be nice to have a better way to handle them. Hopefully it isn't very problematic.

**Comment by IridiumXOR** [comment] 2024-02-27 23:04
A simple ```.replace("__fill__", "")``` on user-side do the job :)
Thank you again!

**Closed as completed** 2024-02-28 00:45 UTC
